version: '3'
services:
  goapp:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - '.:/app'

  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - 4004:4004
    volumes:
      - ./docker/dynamodb:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
  