version: '3'
services:
  goweb:
    container_name: goweb
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - ${WEB_PORT}:${WEB_PORT}
      - 2345:2345
    volumes:
      - '.:/app'

  gocli:
    container_name: gocli
    build:
      context: .
      dockerfile: ./docker/cli/Dockerfile
    volumes:
      - '.:/app'

  firestore:
    build: ./docker/firestore
    env_file:
      - .env
    ports:
      - "8787:8787"
      - "4000:4000"
      - "8788:8787"

  postgres:
    image: postgres:latest
    working_dir: /app
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  