version: '3'
services:
  goapp:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    volumes:
      - '.:/app'

  firestore:
    build: ./docker/firestore
    env_file:
      - .env
    ports:
      - "8787:8787"
      - "4000:4000"
      - "8788:8787"
  